name: Quality

concurrency:
    cancel-in-progress: true
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'

on:
    push:
      branches:
        - main
    pull_request:

permissions:
    contents: read

jobs:
  markdown-lint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: DavidAnson/markdownlint-cli2-action@v13
          with:
            globs: |
              **/*.md
              #**/.terraform/**/*.md
  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
  action-lint:
    name: Action Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Actionlint
      id: get_actionlint
      run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
    - name: Run Actionlint
      run: ${{ steps.get_actionlint.outputs.executable }} -color
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
  mdbook:
    name: Mdbook
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install stable
        rustup default stable
    - name: Install latest mdbook
      run: |
        tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
        url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
        mkdir bin
        curl -sSL "$url" | tar -xz --directory=bin
        echo "$(pwd)/bin" >> "$GITHUB_PATH"
    - name: Run tests
      run: mdbook test
 