name: Release

concurrency:
  cancel-in-progress: false
  group: '${{ github.workflow }}'

on:
  # TODO: remove me before merging
  pull_request: 
  workflow_dispatch:
    inputs:
      release_type:
        description: "Which type of release is this?"
        type: choice
        options:
          - "patch"
          - "minor"
          - "major"
        default: "patch"
          
permissions:
  contents: read

jobs:
  get:
    name: Get versions
    runs-on: ubuntu-latest
    outputs:
      current: ${{ steps.current.outputs.version }}
      next: ${{ steps.next.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Install semver-cli
        run: |-
          go install github.com/maykonlf/semver-cli/cmd/semver@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Get current version
        id: current
        run: echo "version=$(semver get release)" >> "$GITHUB_OUTPUT"
      - name: Get next version
        id: next
        env:
          # TODO: remove 'release' fallback once PR trigger is removed
          FLAG: ${{ inputs.release_type == 'patch' && 'release' || inputs.release_type || 'release' }}
        run: echo "version=$(semver up $FLAG)" >> "$GITHUB_OUTPUT"
  update_files:
    runs-on: ubuntu-latest
    needs: get
    env:
      CURRENT: ${{needs.get.outputs.current}}
      NEXT: ${{needs.get.outputs.next}}
    steps:
      - uses: actions/checkout@v3
      - name: update README.md
        run: sed -i "s/$CURRENT/$NEXT/g" README.md
      - name: update CHANGELOG.md
        env:
          LINE_SPLIT: 5
        run: |-
          head -n "$LINE_SPLIT" CHANGELOG.md > changelog.md.0
          tail -n +"$(($LINE_SPLIT + 1))" CHANGELOG.md > changelog.md.1
          sed -i "s/$CURRENT_HEADER/$NEW_HEADER/g" CHANGELOG.md
          cat changelog.md.0 > CHANGELOG.md
          echo "test" >> CHANGELOG.md
          cat changelog.md.1 >> CHANGELOG.md
      - name: Debug files
        run: |-
          cat README.md
          echo "  "
          cat CHANGELOG.md


        

