name: Release

concurrency:
  cancel-in-progress: false
  group: '${{ github.workflow }}'

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Which type of release is this?"
        type: choice
        options:
          - "patch"
          - "minor"
          - "major"
        default: "patch"
          
permissions:
  contents: read

jobs:
  get:
    name: Get versions
    runs-on: ubuntu-latest
    outputs:
      current: ${{ steps.current.outputs.version }}
      next: ${{ steps.next.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Install semver-cli
        run: go install github.com/maykonlf/semver-cli/cmd/semver@latest
      - name: Get current version
        id: current
        run: echo "version=$(semver get release)" >> "$GITHUB_OUTPUT"
      - name: Get next version
        id: next
        run: echo "version=$(semver up ${{ inputs.release_type == 'patch' && 'release' || inputs.release_type }})" >> "$GITHUB_OUTPUT"
